- name: Download K3S installer
  ansible.builtin.command:
    cmd: "curl -fsSL https://get.k3s.io -o /tmp/k3s-installer.sh"

- name: Ensure K3S installer is executable
  ansible.builtin.file:
    path: /tmp/k3s-installer.sh
    mode: 0755

- name: Install K3S Server
  shell: /tmp/k3s-installer.sh
  when: "'masters' in group_names"

- name: Read K3S Server token
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token_base64
  become: true
  when: "'masters' in group_names"

- name: Store K3S Server token
  ansible.builtin.set_fact:
    node_token: "{{ k3s_token_base64['content'] | b64decode | trim }}"
  when: "'masters' in group_names"

- name: Install K3S Agent
  ansible.builtin.shell:
    cmd: "/tmp/k3s-installer.sh"
  environment:
    K3S_URL: "https://192.168.88.166:6443"
    K3S_TOKEN: "{{ hostvars['bare0']['node_token'] }}"
  when: "'workers' in group_names"

- name: Get K3S config file
  ansible.builtin.slurp:
    src: "/etc/rancher/k3s/k3s.yaml"
  register: k3sconfig_base64
  become: true
  when: "'masters' in group_names"

- name: Write K3S config file
  ansible.builtin.copy:
    content: "{{ k3sconfig_base64.content | b64decode | replace('127.0.0.1', '192.168.88.166') }}"
    dest: "{{ playbook_dir }}/k3s.yaml"
    mode: 0600
  delegate_to: localhost
  run_once: true