external-secrets:
  extraObjects:
  - apiVersion: external-secrets.io/v1beta1
    kind: SecretStore
    metadata:
      name: secretstore-sample
    spec:
      provider:
        aws:
          service: SecretsManager
          region: eu-central-1
          auth:
            secretRef:
              accessKeyIDSecretRef:
                name: awssm-secret
                key: access-key
              secretAccessKeySecretRef:
                name: awssm-secret
                key: secret-access-key

  - apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: test-secret
      namespace: default
    spec:
      refreshInterval: 1h
      secretStoreRef:
        name: secretstore-sample
        kind: SecretStore
      target:
        name: test-secret
        creationPolicy: Owner
      data:
        - secretKey: random_key
          remoteRef:
            key: k3s/test
            property: random_key
