external-secrets:
  extraObjects:
  - apiVersion: external-secrets.io/v1beta1
    kind: ClusterSecretStore
    metadata:
      name: secretstore-sample
      namespace: external-secrets
    spec:
      provider:
        aws:
          service: SecretsManager
          region: eu-central-1
          auth:
            secretRef:
              accessKeyIDSecretRef:
                name: awssm-secret
                key: access-key
                namespace: external-secrets
              secretAccessKeySecretRef:
                name: awssm-secret
                key: secret-access-key
                namespace: external-secrets
      conditions:
        - namespaces:
          - "test-api"

  - apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: test-secret
      namespace: external-secrets
    spec:
      refreshInterval: 1h
      secretStoreRef:
        name: secretstore-sample
        kind: SecretStore
      target:
        name: test-secret
        creationPolicy: Owner
      data:
        - secretKey: random_key
          remoteRef:
            key: k3s/test
            property: random_key
