# apiVersion: v2
# name: homepage
# version: 0.0.0
# dependencies:
#   - name: app-template
#     version: 2.6.0
#     repository: https://bjw-s.github.io/helm-charts

apiVersion: v2
name: homepage
version: 0.0.0
dependencies:
  - name: homepage
    version: 2.0.1
    repository: https://jameswynn.github.io/helm-charts