homepage:
  env:
    LOG_LEVEL: debug

  envFrom:
    - secretRef:
        name: homepage-app-config

  config:
    bookmarks:
      - Homelab:
          - Repository:
              - href: https://github.com/holowieszek/homelab
                icon: github-light.svg

      - Infrastructure:
          - AWS:
              - href: https://holowieszkom.awsapps.com/start/
                icon: aws-light.svg

          - Router:
              - href: http://router-01.internal/
                icon: mikrotik-light.svg

          - Switch:
              - href: http://switch-01.internal/
                icon: netgear-light.svg
    services:
      - Monitoring:
          - Grafana:
              href: https://grafana.internal.mateuszholowieszko.com/
              description: Dashboards
              icon: grafana.svg

          - Speedtest:
              href: https://speedtest.internal.mateuszholowieszko.com/
              icon: speedtest-tracker.png
              widget:
                type: speedtest
                url: http://speedtest.internal.mateuszholowieszko.com
                fields: ["download", "upload", "ping"]

          - Pihole:
              href: http://192.168.88.230
              icon: pi-hole.svg
              widget:
                type: pihole
                url: http://192.168.88.230
                version: 5
                key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"

          - Mikrotik:
              href: http://router-01.internal/
              icon: mikrotik-light.svg
              widget:
                type: mikrotik
                url: http://router-01.internal/
                username: "{{HOMEPAGE_VAR_MIKROTIK_USERNAME}}"
                password: "{{HOMEPAGE_VAR_MIKROTIK_PASSWORD}}"

      - CI/CD:
          - ArgoCD:
              href: https://argocd.internal.mateuszholowieszko.com/
              description: Continuous deployment
              icon: argo-cd.svg

      - Applications:
          - pgadmin:
              href: https://pgadmin.internal.mateuszholowieszko.com/
              description: pgadmin dashboard
              icon: pgadmin.svg
    widgets:
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - search:
          provider: duckduckgo
          target: _blank
    kubernetes:
      mode: cluster
    settings:

  serviceAccount:
    create: true
    name: homepage

  enableRbac: true

  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: internal.mateuszholowieszko.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - internal.mateuszholowieszko.com
          secretName: internal-mateuszholowieszko-com-tls
