homepage:
  config:
    bookmarks:
      - Homelab:
        - Repository:
            - href: https://github.com/holowieszek
              icon: github.svg
              
        - Infrastructure:
          - AWS:
            - href: https://holowieszkom.awsapps.com/start
              icon: aws.svg
              
    services: 
      - Monitoring:
          - Grafana:
              href: https://grafana.internal.mateuszholowieszko.com/
              description: Dashboards
              icon: grafana.svg

      - CI/CD :
          - ArgoCD:
              href: https://argocd.internal.mateuszholowieszko.com/
              description: Continuous deployment

      - My Third Group:
          - My Third Service:
              href: http://localhost/
              description: Homepage is 😎
    widgets:
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - search:
          provider: duckduckgo
          target: _blank
    kubernetes:
      mode: cluster
    settings:

  serviceAccount:
    create: true
    name: homepage

  enableRbac: true

  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: internal.mateuszholowieszko.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - internal.mateuszholowieszko.com
          secretName: internal-mateuszholowieszko-com-tls