app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v0.10.9
  service:
    main:
      ports:
        http:
          port: 80
          targetPort: 3000
          protocol: HTTP
  persistence:
    config:
      enabled: true
      type: configMap
      name: homepage-config
      globalMounts:
        - path: /app/config/settings.yaml
          subPath: settings.yaml
        - path: /app/config/widgets.yaml
          subPath: widgets.yaml
        - path: /app/config/services.yaml
          subPath: services.yaml
        - path: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
  configMaps:
    config:
      enabled: true
      data:
        settings.yaml: |
          cardBlur: md
          theme: dark
          headerStyle: boxed
          hideVersion: true
        widgets.yaml: |
          - kubernetes:
              cluster:
                # Shows cluster-wide statistics
                show: true
                # Shows the aggregate CPU stats
                cpu: true
                # Shows the aggregate memory stats
                memory: true
                # Shows a custom label
                showLabel: true
                label: "cluster"
              nodes:
                # Shows node-specific statistics
                show: true
                # Shows the CPU for each node
                cpu: true
                # Shows the memory for each node
                memory: true
                # Shows the label, which is always the node name
                showLabel: true

          - search:
              provider: google
              target: _blank
        services.yaml: |
          - Development:
            - ArgoCD:
                href: https://argocd.internal.mateuszholowieszko.com
                description: Continuous deployment
                icon: argocd.svg
        bookmarks.yaml: |
          - Homelab:
            - Documentation:
              - href: https://internal.mateuszholowieszko.com
                icon: google-docs.svg
            - Public homelab repository:
              - href: https://github.com/holowieszek/homelab
                icon: github.svg