longhorn:
  defaultSettings:
    backupTarget: s3://homelab-prod-volume-backups
    backupTargetCredentialSecret: longhorn-backup-credentials

  longhornUI:
    replicas: 1

  metrics:
    serviceMonitor:
      enabled: true
