longhorn:
  defaultBackupStore:
    backupTarget: s3://homelab-prod-volume-backups@eu-central-1/testing/
    backupTargetCredentialSecret: longhorn-backup-credentials

  longhornUI:
    replicas: 1

  metrics:
    serviceMonitor:
      enabled: true
