apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-svc-user
  namespace: opnsense-backup
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: aws-svc-user
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/global/config
        property: access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/global/config
        property: secret_access_key
    - secretKey: AWS_ACCOUNT_NUMBER
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/global/config
        property: account_number
