apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: meshcore-telemetry-db-config
  namespace: meshcore-telemetry
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: meshcore-telemetry-db-config
    creationPolicy: Owner
  data:
    - secretKey: dbname
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/databases/meshcore-telemetry/credentials
        property: dbname
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/databases/meshcore-telemetry/credentials
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/databases/meshcore-telemetry/credentials
        property: password
    - secretKey: uri
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/databases/meshcore-telemetry/credentials
        property: uri
    - secretKey: jdbc-uri
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/databases/meshcore-telemetry/credentials
        property: jdbc-uri
