app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: sissbruecker/linkding
            tag: 1.39.1
          env:
            LD_DB_ENGINE: postgres
            LD_DB_HOST: linkding-db-rw.linkding
            LD_DB_PORT: 5432
            # ADMIN_EMAIL:
            #   valueFrom:
            #     secretKeyRef:
            #       name: linkding-app-config
            #       key: admin-email
            # ADMIN_PASSWORD:
            #   valueFrom:
            #     secretKeyRef:
            #       name: linkding-app-config
            #       key: admin-password
            LD_DB_DATABASE:
              valueFrom:
                secretKeyRef:
                  name: linkding-db-config
                  key: dbname
            LD_DB_USER:
              valueFrom:
                secretKeyRef:
                  name: linkding-db-config
                  key: username
            LD_DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: linkding-db-config
                  key: password
  service:
    main:
      ports:
        http:
          port: 9090
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: "traefik"
      hosts:
        - host: linkding.internal.mateuszholowieszko.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - linkding.internal.mateuszholowieszko.com
          secretName: linkding-internal-mateuszholowieszko-com-tls
