apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frigate-cron-sync-role
  namespace: frigate
rules:
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create"]
