apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate-sync-job-config
  namespace: frigate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: frigate-sync-job-config
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: default
        decodingStrategy: none
        metadataPolicy: none
        key: homelab/prod/applications/frigatesyncs/credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        conversionStrategy: default
        decodingStrategy: none
        metadataPolicy: none
        key: homelab/prod/applications/frigatesyncs/credentials
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_DEFAULT_REGION
      remoteRef:
        conversionStrategy: default
        decodingStrategy: none
        metadataPolicy: none
        key: homelab/prod/applications/frigatesyncs/credentials
        property: AWS_DEFAULT_REGION
    - secretKey: AWS_FRIGATE_BACKUP_BUCKET
      remoteRef:
        conversionStrategy: default
        decodingStrategy: none
        metadataPolicy: none
        key: homelab/prod/applications/frigatesyncs/credentials
        property: AWS_FRIGATE_BACKUP_BUCKET