apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate-sync-job-config
  namespace: frigate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: frigate-sync-job-config
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/frigatesyncs/credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/frigatesyncs/credentials
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_DEFAULT_REGION
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/frigatesyncs/credentials
        property: AWS_DEFAULT_REGION
    - secretKey: AWS_FRIGATE_BACKUP_BUCKET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/frigatesyncs/credentials
        property: AWS_FRIGATE_BACKUP_BUCKET
---
apiVersion: v1
kind: Secret
metadata:
  name: frigate-cron-sync-sa-token
  annotations:
    kubernetes.io/service-account.name: frigate-cron-sync-sa
type: kubernetes.io/service-account-token
