apiVersion: batch/v1
kind: CronJob
metadata:
  name: frigate-s3-sync
spec:
  schedule: "* * * * *" # Every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: s3sync
              image: amazon/aws-cli
              command:
                - /bin/sh
                - -c
                - >
                  aws s3 sync /media/frigate/recordings $AWS_FRIGATE_BACKUP_BUCKET
              envFrom:
                - secretRef:
                    name: frigate-sync-job-config
              volumeMounts:
                - name: frigate-media
                  mountPath: /media
          restartPolicy: OnFailure
          volumes:
            - name: frigate-media
              persistentVolumeClaim:
                claimName: frigate-media
