apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm-app-config
  namespace: litellm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: litellm-app-config
    creationPolicy: Owner
  data:
    - secretKey: uri
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/general/credentials
        property: litellm_uri
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/general/credentials
        property: litellm_password
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/general/credentials
        property: litellm_username
    - secretKey: dbname
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/general/credentials
        property: litellm_dbname
    - secretKey: master_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/general/credentials
        property: litellm_master_key
    - secretKey: salt_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/general/credentials
        property: litellm_salt_key
