app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/speedtest-tracker
            tag: latest
          env:
            PUID: 1000
            PGID: 1000
            SPEEDTEST_SCHEDULE: 0 * * * *
            SPEEDTEST_SERVERS: 40572
            APP_KEY:
              valueFrom:
                secretKeyRef:
                  name: speedtest
                  key: app-key
            DB_CONNECTION: pgsql
            DB_HOST: speedtest-db-v3-rw.speedtest
            DB_PORT: 5432
            ADMIN_EMAIL:
              valueFrom:
                secretKeyRef:
                  name: speedtest
                  key: admin-email
            ADMIN_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: speedtest
                  key: admin-password
            DB_DATABASE:
              valueFrom:
                secretKeyRef:
                  name: speedtest-db-v3-app
                  key: dbname
            DB_USERNAME:
              valueFrom:
                secretKeyRef:
                  name: speedtest-db-v3-app 
                  key: user
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: speedtest-db-v3-app 
                  key: password
  service:
    main:
      ports:
        http:
          port: 80
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: "traefik"
      hosts:
        - host: speedtest.internal.mateuszholowieszko.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - speedtest.internal.mateuszholowieszko.com
          secretName: speedtest-internal-mateuszholowieszko-com-tls