apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awssm-secret
  namespace: linkding
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: awssm-secret
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/global/config
        property: access_key_id
    - secretKey: secret-access-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/global/config
        property: secret_access_key
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db
  namespace: linkding
spec:
  instances: 3

  resources:
    requests:
      memory: 256Mi

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  backup:
    barmanObjectStore: &barmanObjectStore
      destinationPath: s3://homelab-prod-database-backups/linkding
      serverName: &currentCluster linkding-db-backup-v2
      s3Credentials:
        accessKeyId:
          name: awssm-secret
          key: access-key-id
        secretAccessKey:
          name: awssm-secret
          key: secret-access-key
      data:
        compression: gzip
      wal:
        compression: gzip
    retentionPolicy: 21d

  bootstrap:
    recovery:
      source: &previousCluster linkding-db-backup-v1

  externalClusters:
    - name: *previousCluster
      barmanObjectStore:
        <<: *barmanObjectStore
        serverName: *previousCluster
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: linkding-db-backup-v2
  namespace: linkding
spec:
  immediate: true
  schedule: "0 0 */6 * * *"
  cluster:
    name: linkding-db
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: linkding-db-app-push
  namespace: linkding
spec:
  updatePolicy: Replace
  deletionPolicy: None
  refreshInterval: 1h
  secretStoreRefs:
    - name: secretstore-sample
      kind: ClusterSecretStore
  selector:
    secret:
      name: linkding-db-app
  data:
    - conversionStrategy: None
      match:
        secretKey: password
        remoteRef:
          remoteKey: homelab/prod/databases/linkding/credentials
          property: password
      metadata:
        secretPushFormat: string
    - conversionStrategy: None
      match:
        secretKey: username
        remoteRef:
          remoteKey: homelab/prod/databases/linkding/credentials
          property: username
      metadata:
        secretPushFormat: string
    - conversionStrategy: None
      match:
        secretKey: dbname
        remoteRef:
          remoteKey: homelab/prod/databases/linkding/credentials
          property: dbname
      metadata:
        secretPushFormat: string
    - conversionStrategy: None
      match:
        secretKey: jdbc-uri
        remoteRef:
          remoteKey: homelab/prod/databases/linkding/credentials
          property: jdbc-uri
      metadata:
        secretPushFormat: string
