emqx:
  replicaCount: 3
  recreatePods: true

  ingress:
    dashboard:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: "traefik"
      hosts:
        - emqx.internal.mateuszholowieszko.com
      path: /
      tls:
        - hosts:
            - emqx.internal.mateuszholowieszko.com
          secretName: emqx-internal-mateuszholowieszko-com-tls
