{
 "title": "Kingsmith Walkingpad",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Duration [h]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    (SUM(time)/60.0)/60.0 AS total_distance\r\nFROM \"Activities\"\r\nWHERE $__timeFilter(start_time);"
    }
   ]
  },
  {
   "title": "Steps",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    SUM(steps) AS total_distance\r\nFROM \"Activities\"\r\nWHERE $__timeFilter(start_time);"
    }
   ]
  },
  {
   "title": "Distance [km]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    SUM(distance)/1000.0 AS total_distance\r\nFROM \"Activities\"\r\nWHERE $__timeFilter(start_time);"
    }
   ]
  },
  {
   "title": "Steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    DATE(start_time) AS run_date,\r\n    SUM(steps) AS total_steps\r\nFROM \"Activities\"\r\nGROUP BY run_date;\r\n"
    }
   ]
  },
  {
   "title": "Distance [km]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    DATE(start_time) AS run_date,\r\n    SUM(distance)/1000.0 AS total_distance\r\nFROM \"Activities\"\r\nGROUP BY run_date;\r\n"
    }
   ]
  }
 ]
}