grafana:
  admin:
    existingSecret: "grafana"
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: monitoring
    datasources:
      enabled: true
      searchNamespace: monitoring
  grafana.ini:
    server:
      root_url: https://internal.homelab/grafana
  dashboards:
    default:
      k3s:
        gnetId: 15282
        revision: 1
        datasource: Prometheus