grafana:
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: monitoring
    datasources:
      enabled: true
      searchNamespace: monitoring
  # grafana.ini:
  #   server:
  #     root_url: https://internal.homelab/grafana