grafana:
  envFromSecret: postgres-datasources-config

  admin:
    existingSecret: "grafana"

  sidecar:
    dashboards:
      enabled: true
      searchNamespace: monitoring
    datasources:
      enabled: true
      searchNamespace: monitoring

  grafana.ini:
    server:
      root_url: https://grafana.internal.mateuszholowieszko.com

  # datasources:
  #   datasources.yaml:

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: "default"
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      k3s:
        gnetId: 15282
        revision: 1
        datasource: Prometheus

      cloudnative-pg:
        gnetId: 20417
        revision: 3
        datasource: Prometheus

      cert-manager:
        gnetId: 20842
        revision: 3
        datasource: Prometheus
