apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-app-config
  namespace: speedtest
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: speedtest-app-config
    creationPolicy: Owner
  data:
    - secretKey: pihole-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/pihole/credentials
        property: password
    - secretKey: mikrotik-username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/mikrotik/credentials
        property: username
    - secretKey: mikrotik-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/mikrotik/credentials
        property: password
