apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-app-config
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: homepage-app-config
    creationPolicy: Owner
  data:
    - secretKey: PIHOLE_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/pihole/credentials
        property: password
    - secretKey: MIKROTIK_USERNAME
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/mikrotik/credentials
        property: username
    - secretKey: MIKROTIK_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/mikrotik/credentials
        property: password
