external-secrets:
  extraObjects:
    - apiVersion: external-secrets.io/v1beta1
      kind: ClusterSecretStore
      metadata:
        name: secretstore-sample
        namespace: external-secrets
      spec:
        provider:
          aws:
            service: SecretsManager
            region: eu-central-1
            auth:
              secretRef:
                accessKeyIDSecretRef:
                  name: awssm-secret
                  key: access-key
                  namespace: external-secrets
                secretAccessKeySecretRef:
                  name: awssm-secret
                  key: secret-access-key
                  namespace: external-secrets
        conditions:
          - namespaces:
              - "cert-manager"
              - "test-api"
              - "speedtest"
              - "argocd"
              - "grafana"
              - "homepage"
              - "linkding"
              - "longhorn"
              - "kingsmith"
    - apiVersion: external-secrets.io/v1alpha1
      kind: PushSecret
      metadata:
        name: argocd-secrets-push
        namespace: argocd
      spec:
        updatePolicy: Replace
        deletionPolicy: None
        refreshInterval: 10m
        secretStoreRefs:
          - name: secretstore-sample
            kind: ClusterSecretStore
        selector:
          secret:
            name: argocd-initial-admin-secret
        data:
          - conversionStrategy: None
            match:
              secretKey: password
              remoteRef:
                # remoteKey:
                remoteKey: homelab/prod/applications/argocd/credentials
                property: argocd_password
            metadata:
              secretPushFormat: string
