apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-default
spec:
  cron: "0 */6 * * *"
  task: snapshot
  retain: 4
  concurrency: 5
  labels:
    interval: 6h
  groups:
    - snapshot-default
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-default
spec:
  cron: "0 */6 * * *"
  task: backup
  retain: 4
  concurrency: 5
  labels:
    interval: 6h
  groups:
    - backup-default
