app-template:
  controllers:
    main:
      replicas: 1
      containers:
        main:
          image:
            repository: docker.io/dpage/pgadmin4
            tag: latest
          env:
            PGADMIN_DEFAULT_EMAIL: test@example.com
            PGADMIN_DEFAULT_PASSWORD: testpassword
          user: "$UID:$GID"
          securityContext:
            runAsUser: 5050
            runAsGroup: 5050
      initContainers:
        - name: pgadmin-data-permission-fix
          image: busybox
          command: ["/bin/chown", "-R", "5050:5050", "/var/lib/pgadmin"]
          volumeMounts:
            - name: pgadminstorage
              mountPath: /var/lib/pgadmin

  service:
    main:
      ports:
        http:
          port: 80
          protocol: HTTP

  ingress:
    main:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: "traefik"
      hosts:
        - host: pgadmin.internal.mateuszholowieszko.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - pgadmin.internal.mateuszholowieszko.com
          secretName: pgadmin-internal-mateuszholowieszko-com-tls

  # podSecurityContext:
  #   runAsUser: 5050
  #   runAsGroup: 5050
  #   fsGroup: 5050
  #   fsGroupChangePolicy: OnRootMismatch

  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 1Gi
      advancedMounts:
        main:
          main:
            - path: /var/lib/pgadmin
              subPath: pgadmin

    # data:
    #   accessMode: ReadWriteOnce
    #   advancedMounts:
    #     main:
    #       main:
    #         - path: /var/lib/pgadmin
    #           subPath: pgadmin
