app-template:
  controllers:
    main:
      enabled: false
      replicas: 1
      pod:
        securityContext:
          runAsUser: 5050
          runAsGroup: 5050
          fsGroup: 5050
          fsGroupChangePolicy: OnRootMismatch
      containers:
        main:
          image:
            repository: docker.io/dpage/pgadmin4
            tag: latest
          env:
            PGADMIN_DEFAULT_EMAIL: test@example.com
            PGADMIN_DEFAULT_PASSWORD: testpassword

  service:
    main:
      ports:
        http:
          port: 80
          protocol: HTTP

  ingress:
    main:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: "traefik"
      hosts:
        - host: pgadmin.internal.mateuszholowieszko.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - pgadmin.internal.mateuszholowieszko.com
          secretName: pgadmin-internal-mateuszholowieszko-com-tls

  # podSecurityContext:
  #   runAsUser: 5050
  #   runAsGroup: 5050
  #   fsGroup: 5050
  # fsGroupChangePolicy: OnRootMismatch

  persistence:
    data:
      enabled: true
      # enabled: false
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 1Gi
      # existingClaim: pgadmin-data-restore
      globalMounts:
        - path: /var/lib/pgadmin
      # advancedMounts:
      #   main:
      #     main:
      #       - path: /var/lib/pgadmin
      #         subPath: pgadmin
