apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: speedtest
  namespace: speedtest
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: speedtest
    creationPolicy: Owner
  data:
    - secretKey: app-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: k3s/homelab/globalsecrets
        property: speedtest_app_key
    - secretKey: admin-email
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: k3s/homelab/globalsecrets
        property: speedtest_admin_email
    - secretKey: admin-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: k3s/homelab/globalsecrets
        property: speedtest_admin_password