apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: speedtest
  namespace: speedtest
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: speedtest
    creationPolicy: Owner
  data:
    - secretKey: app-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: k3s/homelab/globalsecrets
        property: speedtest_app_key
    - secretKey: admin-email
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: k3s/homelab/globalsecrets
        property: speedtest_admin_email
    - secretKey: admin-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: k3s/homelab/globalsecrets
        property: speedtest_admin_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: speedtest-db-config
  namespace: speedtest
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: speedtest-db-config
    creationPolicy: Owner
  data:
    - secretKey: dbname
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/databases/speedtest-db/credentials
        property: dbname
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/databases/speedtest-db/credentials
        property: password
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/databases/speedtest-db/credentials
        property: username