apiVersion: v1
kind: ConfigMap
metadata:
  name: test-app
  namespace: test-app
data:
  index.html: |
    <html>
    <head>
      <title>Hello World!</title>
    </head>
    <body>Test App v3!</body>
    </html>
