---
apiVersion: v1
kind: Namespace
metadata:
  name: test-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-app
  namespace: test-app
data:
  index.html: |
    <html>
    <head>
      <title>Hello World!</title>
    </head>
    <body>Test App v3!</body>
    </html>
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-app
  namespace: test-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
  - host: test-app.internal.mateuszholowieszko.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-app
            port:
              number: 80
  tls:
  - hosts:
      - test-app.internal.mateuszholowieszko.com
    secretName: test-app-internal-mateuszholowieszko-com-tls
---
apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: test-app
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: test-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-nginx
  namespace: test-app
spec:
  selector:
    matchLabels:
      app: test-app
  replicas: 1
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: test-app-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: test-app-volume
        configMap:
          name: test-app