apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-creds-ssh-creds
  namespace: argocd
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: argocd-repo-creds-ssh-creds
    creationPolicy: Owner
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/git/private/credentials
        property: SSH_PRIVATE_KEY
    - secretKey: url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/git/private/credentials
        property: REPO_GIT_URL
