apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api-nginx
  namespace: test-api
spec:
  selector:
    matchLabels:
      app: test-api
  replicas: 3
  template:
    metadata:
      labels:
        app: test-api
    spec:
      containers:
        - name: quick-test-node-api
          image: ghcr.io/holowieszek/quick-test-node-api:@sha256:943db196c93793186c87078119438f2216e8c8fc5afb654d2d8e03b9e3607f60
          ports:
            - containerPort: 3000
          env:
            - name: TEST_ENV_VAR
              valueFrom:
                secretKeyRef:
                  name: test-api-secret
                  key: random_key
            - name: LOG_LEVEl
              valueFrom:
                secretKeyRef:
                  name: test-api-another-secret
                  key: LOG_LEVEL
