apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-api-secret
  namespace: test-api
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: test-api-secret
    creationPolicy: Owner
  data:
    - secretKey: random_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: k3s/test
        property: random_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-api-secret-2
  namespace: test-api
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: test-api-another-secret
    creationPolicy: Owner
  data:
    - secretKey: LOG_LEVEL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: k3s/test-another-test
        property: LOG_LEVEL
