---
apiVersion: v1
kind: Namespace
metadata:
  name: test-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-api
  namespace: test-api
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
  - host: test-api.internal.homelab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-api
            port:
              number: 80
  tls:
  - hosts:
      - test-api.internal.mateuszholowieszko.com
    secretName: test-api.internal-mateuszholowieszko-com-tls
---
apiVersion: v1
kind: Service
metadata:
  name: test-api
  namespace: test-api
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: test-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api-nginx
  namespace: test-api
spec:
  selector:
    matchLabels:
      app: test-api
  replicas: 3
  template:
    metadata:
      labels:
        app: test-api
    spec:
      containers:
      - name: quick-test-node-api
        image: ghcr.io/holowieszek/quick-test-node-api:main
        ports:
        - containerPort: 3000
        env:
        - name: TEST_ENV_VAR
          valueFrom:
            secretKeyRef:
              name: test-api-secret
              key: random_key
        - name: LOG_LEVEl
          valueFrom:
            secretKeyRef:
              name: test-api-another-secret
              key: LOG_LEVEL
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-api-secret
  namespace: test-api
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: test-api-secret
    creationPolicy: Owner
  data:
    - secretKey: random_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: k3s/test
        property: random_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-api-secret-2
  namespace: test-api
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: test-api-another-secret
    creationPolicy: Owner
  data:
    - secretKey: LOG_LEVEL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: k3s/test-another-test
        property: LOG_LEVEL