apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-app-config
  namespace: linkding
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: linkding-app-config
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/linkding/credentials
        property: username
    - secretKey: admin-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/linkding/credentials
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-db-config
  namespace: linkding
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: linkding-db-config
    creationPolicy: Owner
  data:
    - secretKey: dbname
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/databases/linkding/credentials
        property: dbname
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/databases/linkding/credentials
        property: password
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/databases/linkding/credentials
        property: username
