apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-cloudflare-tunnel
  namespace: cloudflared
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: cloudflared-cloudflare-tunnel
    creationPolicy: Owner
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        # key: k3s/homelab/globalsecrets
        key: homelab/prod/system/cloudflare/credentials
        property: tunnel_token
