frigate:
  config: |
    mqtt:
      host: "emqx.internal.mateuszholowieszko.com"
      port: 1883
    go2rtc:
      streams:
        back:
          - rtsp://testtest:testtest@192.168.88.78:554/stream1
    cameras:
      back:
        ffmpeg:
          inputs:
            - path: rtsp://testtest:testtest@192.168.88.78:554/stream1
              output_args: preset-record-generic-audio-copy
              roles:
                - record 
        detect:
          enabled: false
        record:
          enabled: true
          retain:
            days: 3
            mode: all
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: "traefik"
    # rules:
    #   - host: frigate.internal.mateuszholowieszko.com
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         portName: http
    hosts:
      - host: frigate.internal.mateuszholowieszko.com
        paths:
          - path: /
            portName: http
            # backend:
            #   service:
            #     name: frigate
            #     port:
            #       name: http
    tls:
      - hosts:
          - frigate.internal.mateuszholowieszko.com
        secretName: frigate-internal-mateuszholowieszko-com-tls

  persistence:
    media:
      enabled: true
      storageClass: longhorn
      size: 10Gi
