frigate:
  config: |
    mqtt:
      host: "emqx.internal.mateuszholowieszko.com"
      port: 1883
    go2rtc:
      streams:
        back:
          - rtsp://192.168.88.77:8080/h264.sdp
    cameras:
      back:
        ffmpeg:
          inputs:
            - path: rtsp://192.168.88.77:8080/h264.sdp
              roles:
                - record

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: "traefik"
    # rules:
    #   - host: frigate.internal.mateuszholowieszko.com
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         portName: http
    hosts:
      - host: frigate.internal.mateuszholowieszko.com
        paths:
          - path: /
            portName: http
            # backend:
            #   service:
            #     name: frigate
            #     port:
            #       name: http
    tls:
      - hosts:
          - frigate.internal.mateuszholowieszko.com
        secretName: frigate-internal-mateuszholowieszko-com-tls
