frigate:
  config: |
    mqtt:
      host: "emqx.internal.mateuszholowieszko.com"
      port: 1883
      user: ""
      password: ""
    cameras:
      back:
        ffmpeg:
          inputs:
            - path: rtsp://192.168.88.47:8080/h264.sdp
              roles:
                - detect
  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: "traefik"
    rules:
      - host: frigate.internal.mateuszholowieszko.com
        paths:
          - path: /
            pathType: Prefix
            portName: http
            # backend:
            #   service:
            #     name: frigate
            #     port:
            #       name: http
    tls:
      - hosts:
          - frigate.internal.mateuszholowieszko.com
        secretName: frigate-internal-mateuszholowieszko-com-tls