home-assistant:
  configuration:
    enabled: true
    trusted_proxies:
      - 10.42.0.0/16

  initContainers:
    - name: init-hacs
      image: bash
      command:
        [
          "bash",
          "-c",
          "pwd && ls -la && cd /config && wget -O - https://get.hacs.xyz | bash -",
        ]
      volumeMounts:
        - mountPath: /config
          name: home-assistant

  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: "traefik"
    hosts:
      - host: home-assistant.internal.mateuszholowieszko.com
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
              port: http
    tls:
      - hosts:
          - home-assistant.internal.mateuszholowieszko.com
        secretName: home-assistant-internal-mateuszholowieszko-com-tls

  persistence:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: longhorn
    #annotations:
    #  longhorn.io/recurring-job-group: "backup-default"
    size: 10Gi
    #existingClaim:
    globalMounts:
      - path: /config
