apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        route53:
          region: eu-central-1
          accessKeyIDSecretRef:
            name: cluster-issuer-r53-credentials
            key: access-key-id
          secretAccessKeySecretRef:
            name: cluster-issuer-r53-credentials
            key: secret-access-key
      selector:
        dnsZones:
        - 'internal.mateuszholowieszko.com'
        - '*.internal.mateuszholowieszko.com'