apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-issuer-r53-credentials
  namespace: cert-manager
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: cluster-issuer-r53-credentials
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        # key: k3s/homelab/globalsecrets
        key: homelab/prod/applications/certmanager/credentials
        property: cluster_issuer_access_key_id
    - secretKey: secret-access-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        # key: k3s/homelab/globalsecrets
        key: homelab/prod/applications/certmanager/credentials
        property: cluster_issuer_secret_access_key
