apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opnsense-backup-cronjob-rolebinding
  namespace: opnsense-backup
subjects:
  - kind: ServiceAccount
    name: opnsense-backup-cronjob-sa
    namespace: opnsense-backup
roleRef:
  kind: Role
  name: opnsense-backup-cronjob-role
  apiGroup: rbac.authorization.k8s.io
