apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opnsense-backup-cronjob-role
  namespace: opnsense-backup
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
