apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opnsense-backup-secret
  namespace: opnsense-backup
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: opnsense-backup-secret
    creationPolicy: Owner
  data:
    - secretKey: BACKUP_API_URL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/opnsensebackups/credentials
        property: BACKUP_API_URL
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/opnsensebackups/credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/opnsensebackups/credentials
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_REGION
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/opnsensebackups/credentials
        property: AWS_REGION
    - secretKey: S3_BUCKET_NAME
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/opnsensebackups/credentials
        property: S3_BUCKET_NAME
    - secretKey: OPNSENSE_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/opnsensebackups/credentials
        property: OPNSENSE_API_KEY
    - secretKey: OPNSENSE_SECRET_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/applications/opnsensebackups/credentials
        property: OPNSENSE_SECRET_KEY