apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudlog-nginx
  namespace: cloudlog
spec:
  selector:
    matchLabels:
      app: cloudlog
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudlog
    spec:
      containers:
        - name: cloudlog
          image: public.ecr.aws/h4u5l0d7/homelab-prod-ecr-cloudlog:2.8.8
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: cloudlog-secret
                  key: dbname

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: cloudlog-secret
                  key: username

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudlog-secret
                  key: password

            - name: MYSQL_HOST
              value: cloudlog-db-rw.cloudlog

            - name: MYSQL_PORT
              value: "5432"

            - name: BASE_LOCATOR
              value: KO13OC

            - name: WEBSITE_URL
              value: https://cloudlog.internal.mateuszholowieszko.com

            - name: DIRECTORY
              value: /var/www/html
      volumes:
        - name: cloudlog-storage
          persistentVolumeClaim:
            claimName: cloudlog-data