apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudlog-secret
  namespace: cloudlog
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: cloudlog-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/databases/cloudlog/credentials
        property: password

    - secretKey: dbname
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/databases/cloudlog/credentials
        property: dbname

    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homelab/prod/databases/cloudlog/credentials
        property: username