apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awssm-secret
  namespace: speedtest
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: awssm-secret
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: k3s/homelab/globalsecrets
        property: access_key_id
    - secretKey: secret-access-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: k3s/homelab/globalsecrets
        property: secret_access_key
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: speedtest-db
  namespace: speedtest
spec:
  instances: 3
  resources:
    requests:
      memory: 100Mi

  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true

  backup:
    barmanObjectStore: &barmanObjectStore
      destinationPath: s3://homelab-db-backup-prod/speedtest
      serverName: &currentCluster speedtest-backup-v1
      s3Credentials:
        accessKeyId:
          name: awssm-secret
          key: access-key-id
        secretAccessKey:
          name: awssm-secret
          key: secret-access-key
      data:
        compression: gzip
      wal:
        compression: gzip

  # bootstrap:
  #   recovery:
  #     backup:
  #       name: &previousCluster speedtest-backup-v0

  externalClusters:
    - name: *previousCluster
      barmanObjectStore:
        <<: *barmanObjectStore
        serverName: *previousCluster
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: speedtest-db-v1
  namespace: speedtest
spec:
  immediate: true
  schedule: "0 * * * *"
  backupOwnerReference: cluster
  cluster:
    name: speedtest-db-v1