apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awssm-secret
  namespace: speedtest
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: awssm-secret
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: k3s/homelab/globalsecrets
        property: access_key_id
    - secretKey: secret-access-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: k3s/homelab/globalsecrets
        property: secret_access_key
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: speedtest-db-v1
  namespace: speedtest
spec:
  instances: 3
  resources:
    requests:
      memory: 100Mi

  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true

  bootstrap:
    recovery:
      source: speedtest
      database: speedtest

  externalClusters:
    - name: speedtest
      barmanObjectStore:
        destinationPath: s3://homelab-db-backup-prod/speedtest
        # restore v2
        serverName: speedtest-db-v0
        s3Credentials:
          accessKeyId:
            name: awssm-secret
            key: access-key-id
          secretAccessKey:
            name: awssm-secret
            key: secret-access-key
        # data:
        #   compression: gzip
        # wal:
        #   compression: gzip

  backup:
    barmanObjectStore:
      destinationPath: s3://homelab-db-backup-prod/speedtest
      s3Credentials:
        accessKeyId:
          name: awssm-secret
          key: access-key-id
        secretAccessKey:
          name: awssm-secret
          key: secret-access-key
      data:
        compression: gzip
      wal:
        compression: gzip
# ---
# apiVersion: postgresql.cnpg.io/v1
# kind: ScheduledBackup
# metadata:
#   name: speedtest-db
#   namespace: speedtest
# spec:
#   immediate: true
#   schedule: "* * * * *"
#   backupOwnerReference: cluster
#   cluster:
#     name: speedtest-db-v1