apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awssm-secret
  namespace: speedtest
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: awssm-secret
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: k3s/homelab/globalsecrets
        property: access_key_id
    - secretKey: secret-access-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: k3s/homelab/globalsecrets
        property: secret_access_key
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: cluster-backup
#   namespace: speedtest
# spec:
#   refreshInterval: 10m
#   secretStoreRef:
#     name: secretstore-sample
#     kind: ClusterSecretStore
#   target:
#     name: cluster-backup
#     creationPolicy: Owner
#   data:
#     - secretKey: destination-path
#       remoteRef:
#         conversionStrategy: Default
#         decodingStrategy: None
#         metadataPolicy: None
#         key: k3s/homelab/globalsecrets
#         property: database_backup_destination
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: speedtest-db-v3
  namespace: speedtest
spec:
  instances: 3
  resources:
    requests:
      memory: 100Mi

  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true

  bootstrap:
    recovery:
      source: speedtest-db 
      database: speedtest-db

  externalClusters:
    - name: speedtest-db
      barmanObjectStore:
        destinationPath: s3://homelab-db-backup-prod/speedtest
        # restore v2
        serverName: speedtest-db-v2
        s3Credentials:
          accessKeyId:
            name: awssm-secret
            key: access-key-id
          secretAccessKey:
            name: awssm-secret
            key: secret-access-key
        data:
          compression: gzip
        wal:
          compression: gzip

  # backup:
  #   barmanObjectStore:
  #     destinationPath: s3://homelab-db-backup-prod/speedtest
  #     s3Credentials:
  #       accessKeyId:
  #         name: awssm-secret
  #         key: access-key-id
  #       secretAccessKey:
  #         name: awssm-secret
  #         key: secret-access-key
  #     data:
  #       compression: gzip
  #     wal:
  #       compression: gzip