argo-cd:
  global:
    domain: argocd.internal.mateuszholowieszko.com
  configs:
    params:
      server.insecure: true

    cm:
      timeout.reconciliation: 5m
      
    repositories:
      test-repo:
        url: &repoURL https://github.com/holowieszek/homelab
        name: homelab
        type: git

argocd-apps:
  applicationsets:
    root:
      namespace: argocd
      generators:
        - git:
            repoURL: *repoURL
            revision: &revision main
            directories:
              - path: apps/*
              - path: system/*
              - path: platform/*
      template:
        metadata:
          name: '{{path.basename}}'
        spec:
          destination:
            name: in-cluster
            namespace: '{{path.basename}}'
          project: default
          source:
            repoURL: *repoURL
            path: '{{path}}'
            targetRevision: *revision
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            retry:
              limit: 10
              backoff:
                duration: 1m
                factor: 2
                maxDuration: 16m
            syncOptions:
              - CreateNamespace=true
              - ApplyOutOfSyncOnly=true
              - ServerSideApply=true
            managedNamespaceMetadata:
              annotations:
                # Enable privileged VolSync movers by default for all namespaces
                # TODO this may be refactored in the future for finer granularity
                # See also https://volsync.readthedocs.io/en/stable/usage/permissionmodel.html
                volsync.backube/privileged-movers: "true"