argo-cd:
  global:
    domain: argocd.internal.mateuszholowieszko.com
  configs:
    params:
      server.insecure: true
      controller.diff.server.side: true

    cm:
      timeout.reconciliation: 5m
      resource.ignoreResourceUpdatesEnabled: true
      resource.customizations.ignoreResourceUpdates.all: |
        jsonPointers:
          - /status

    repositories:
      homelab-public:
        url: &publicRepositoryURL https://github.com/holowieszek/homelab
        name: homelab
        type: git
      # homelab-private:
      #   url: &privateRepositoryURL git@github.com:holowieszek/homelab-private.git
      #   name: homelab-private
      #   type: git

argocd-apps:
  applicationsets:
    root:
      namespace: argocd
      generators:
        - git:
            repoURL: *publicRepositoryURL
            revision: &publicRepositoryRevision main
            directories:
              - path: apps/*
              - path: system/*
              - path: platform/*
              - path: databases/*
        # - git:
        #     repoURL: *privateRepositoryURL
        #     revision: &privateRepositoryRevision main
        #     directories:
        #       - path: apps/*
      template:
        metadata:
          name: "{{path.basename}}"
        spec:
          destination:
            name: in-cluster
            namespace: "{{path.basename}}"
          project: default
          sources:
            - repoURL: *publicRepositoryURL
              path: "{{path}}"
              targetRevision: *publicRepositoryRevision
            - repoURL: *privateRepositoryURL
              path: "{{path}}"
              targetRevision: *privateRepositoryRevision
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            retry:
              limit: 10
              backoff:
                duration: 1m
                factor: 2
                maxDuration: 16m
            syncOptions:
              - CreateNamespace=true
              - ApplyOutOfSyncOnly=true
              - ServerSideApply=true
            managedNamespaceMetadata:
              annotations:
                # Enable privileged VolSync movers by default for all namespaces
                # TODO this may be refactored in the future for finer granularity
                # See also https://volsync.readthedocs.io/en/stable/usage/permissionmodel.html
                volsync.backube/privileged-movers: "true"
